version: '3.3'

services:
  redis:
    image: redis
  app:
    image: github_explore_plus:latest
    restart: always
    ports:
      - 127.0.0.1:8001:8000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
